### ISSUE TITLE
Using multiboxing and unhooking

### ISSUE THREAD

**Issue by FredTheNoob** [TheBlacklock/gtautofarmer#1]
I am unsure whether I am the only one experiencing this issue, but when I build and run your program as administrator, and then set multibox to "on" and proceed to open two GT clients, the application window and everything on the screen is unclickable

I seemed to have resolved getting out of there, using CTRL+ALT+Del and them terminating the clients + the program individually. 

It seems the focus is locked onto the one steerable growtopia application for some reason

**Comment by FredTheNoob** [comment]
Also, to add to this it seems that the clients are sometimes out of sync? And are punching different places

**Comment by Blacklock** [comment]
Oh, I never actually finished the multiboxing feature, not sure about the clients going out of sync.

This is actually my first C# project, and I just made the whole thing just for the learning experience. I might come back to properly rewrite it and add multiboxing in a few months when I'm finished with my current project.

**Comment by FredTheNoob** [comment]
Alright. If you would like to collaborate with me on the expansion/improved version of this project at some point, I've already started working on it (a fork). Hit me up on discord (FredTheNoob#1646) if you're interested :D
