### ISSUE TITLE
Found viruses in exe

### ISSUE THREAD

**Issue by imtrynalearn** [TheBlacklock/gtautofarmer#14]
https://www.virustotal.com/gui/file/b3ebfe5b1deca74994c7b3d337f23d4cc2ec518b2bc20e074ce27a083318c213/detection

**Comment by DefaultO** [comment]
@imtrynalearn, well done posting false positives. Look at the source. There literally is nothing hidden in it. Go make yourself clear, that this tool is not even close to a _virus_.

**Comment by Blacklock** [comment]
Sigh.
