### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by smoothAEON** [TheBlacklock/gtautofarmer#2]
No .exe file

**Comment by Blacklock** [comment]
Get Visual Studio and compile the source yourself

**Comment by rizbud16** [comment]
> Get Visual Studio and compile the source yourself

how to compile it?

**Comment by ghost** [comment]
Compiling is the easiest part of this. Firstly, download Visual Studio (Community edition). After you downloading VS installer, open this file and tick ".NET Desktop development". Then, you'll need this autofarmer's ZIP file. After you downloading this auto farmer as a ZIP file, open it and click the VS solution file(.sln) and open it with Visual Studio. Lastly, after opening VS, click the button "Compile" in the upside and select "Compile Solution". Then, you can get and use your file as an .exe file in the section "Output". File location will be written in the Output. That's all, dude :)

**Comment by Blacklock** [comment]
^
