### ISSUE TITLE
No explanations on the different modes

### ISSUE THREAD

**Issue by kassudevv** [TheBlacklock/gtautofarmer#4]
I compiled, etc and everything seems to be working, but I have no idea what the different modes do and overall how to use the thing. Please close this issue with your discord or reply with explanations on what the modes do, thank you. :)

**Comment by Blacklock** [comment]
I can remember only the "Magplant" mode being implemented when I stopped working on the project (apparently some other group of people started developing it further - issue #1).

All it did was press the punch button and place blocks in front of itself with default zoom. Feel free to check out the code [here](https://github.com/Blacklock/gtautofarmer/blob/multiboxing/Autofarmer/Autofarm.cs#L524) if you wanna try and make sense of it.
