### ISSUE TITLE
Multiboxing Issue

### ISSUE THREAD

**Issue by ghost** [TheBlacklock/gtautofarmer#5]
My desktop and other programs are being totally unclickable when I open Multiboxing feature. But it's fixing when I quit from all opened Growtopias. 

Also I don't understand much thing when I look at the codes. I'm already an amateur in C Sharp. 
So, what's wrong in this codes? How I can fix this issue?

**Comment by Blacklock** [comment]
As the README says, the multiboxing feature was never really finished and was a huge mess when I stopped working on it.
